# THIS FILE IS EXCLUSIVELY MAINTAINED by the project aedev.project_tpls v0.3.96
image: python:3.12





.check_rules: &check-rules
  rules:
    - if: $CI_COMMIT_BRANCH == "develop"
      when: never
    - if: $CI_COMMIT_BRANCH =~ /^release/
      when: never
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH

integrity:
  <<: *check-rules
  before_script:
    - python --version
    - pip --version
    - pip install --upgrade pip pipx setuptools
    - pip --version
    - >
      pip install --upgrade --force-reinstall --uploaded-prior-to=P9D
      -r requirements.txt
      -r tests/requirements.txt
    - pip install --upgrade --force-reinstall ae_base ae_paths ae_core ae_shell ae_managed_files aedev_base aedev_commands
  script:
    - pipx run --spec aedev_project_manager project-manager -v check-integrity
  artifacts:
    paths:
      - mypy_report/
      - .pylint/
      - htmlcov/
      - .pytest_cache

pages:
  stage: deploy
  dependencies:
    - integrity
  <<: *check-rules
  script:
    - ls -l -R
    - mkdir -p public/coverage
    - mv -f -v htmlcov/* public/coverage
    - mv -f -v .pytest_cache/coverage.svg public/
    - mv -f -v mypy_report/lineprecision.txt public/
    - mv -f -v mypy_report/mypy.svg public/
    - mv -f -v .pylint/pylint.svg public/
    - mv -f -v .pylint/pylint.log public/
  artifacts:
    paths:
      - public


pypi_deploy:
  stage: deploy
  rules:
    # - if: $CI_COMMIT_TAG =~ /^v?[0-9]+[.][0-9]+([.][0-9]+)?$/
    # CI_COMMIT_TAG is only set if the push does contain a new tag (and no new commit); separate push and rules are
    # additionally creating duplicate jobs on gitlab CI - finally using release branch to trigger deploy.
    - if: $CI_COMMIT_BRANCH =~ /^release/
  variables:
    # the pushed branch has to be a protected branch in order to get the CI variables for the twine/PyPI authentication.
    TWINE_USERNAME: $PYPI_USERNAME
    TWINE_PASSWORD: $PYPI_PASSWORD
  before_script:
     - pip install --upgrade build pip twine
     - python -m build
  script:
    # use test.pypi.org for integration/unit test projects (if is under :data:`~aedev.base.TEST_PROJECTS_PARENT_FOLDER`)
    - twine upload --verbose dist/*
